---
# vars file for rhel-cis
var_system_crypto_policy: !!str DEFAULT
inactivity_timeout_value: !!str 900
var_screensaver_lock_delay: !!str 5
var_sudo_logfile: !!str /var/log/sudo.log
var_sudo_timestamp_timeout: !!str 5
var_authselect_profile: !!str sssd
login_banner_text: !!str ^(Authorized[\s\n]+uses[\s\n]+only\.[\s\n]+All[\s\n]+activity[\s\n]+may[\s\n]+be[\s\n]+monitored[\s\n]+an[\s\n]+reported\.|^(?!.*(\\|fedora|rhel|sle|ubuntu)).*)$
remote_login_banner_text: !!str ^(Authorized[\s\n]+uses[\s\n]+only\.[\s\n]+All[\s\n]+activity[\s\n]+may[\s\n]+be[\s\n]+monitore[\s\n]+and[\s\n]+reported\.|^(?!.*(\\|fedora|rhel|sle|ubuntu)).*)$
motd_banner_text: !!str ^(Authorized[\s\n]+uses[\s\n]+only\.[\s\n]+All[\s\n]+activity[\s\n]+may[\s\n]+be[\s\n]+monitored[\s\n]+an[\s\n]+reported\.|^(?!.*(\\|fedora|rhel|sle|ubuntu)).*)$
var_password_pam_remember: !!str 5
var_password_pam_remember_control_flag: !!str requisite,required
var_accounts_passwords_pam_faillock_deny: !!str 3
var_accounts_passwords_pam_faillock_unlock_time: !!str 900
var_password_pam_minclass: !!str 4
var_password_pam_minlen: !!str 14
var_password_pam_retry: !!str 3
var_password_hashing_algorithm: !!str SHA512
var_account_disable_post_pw_expiration: !!str 30
var_accounts_maximum_age_login_defs: !!str 365
var_accounts_minimum_age_login_defs: !!str 1
var_accounts_password_warn_age_login_defs: !!str 7
var_pam_wheel_group_for_su: !!str sugroup
var_accounts_tmout: !!str 900
var_accounts_user_umask: !!str 027
sysctl_net_ipv6_conf_all_accept_ra_value: !!str 0
sysctl_net_ipv6_conf_all_accept_redirects_value: !!str 0
sysctl_net_ipv6_conf_all_accept_source_route_value: !!str 0
sysctl_net_ipv6_conf_all_forwarding_value: !!str 0
sysctl_net_ipv6_conf_default_accept_ra_value: !!str 0
sysctl_net_ipv6_conf_default_accept_redirects_value: !!str 0
sysctl_net_ipv6_conf_default_accept_source_route_value: !!str 0
sysctl_net_ipv4_conf_all_accept_redirects_value: !!str 0
sysctl_net_ipv4_conf_all_accept_source_route_value: !!str 0
sysctl_net_ipv4_conf_all_log_martians_value: !!str 1
sysctl_net_ipv4_conf_all_rp_filter_value: !!str 1
sysctl_net_ipv4_conf_all_secure_redirects_value: !!str 0
sysctl_net_ipv4_conf_default_accept_redirects_value: !!str 0
sysctl_net_ipv4_conf_default_accept_source_route_value: !!str 0
sysctl_net_ipv4_conf_default_log_martians_value: !!str 1
sysctl_net_ipv4_conf_default_rp_filter_value: !!str 1
sysctl_net_ipv4_conf_default_secure_redirects_value: !!str 0
sysctl_net_ipv4_icmp_echo_ignore_broadcasts_value: !!str 1
sysctl_net_ipv4_icmp_ignore_bogus_error_responses_value: !!str 1
sysctl_net_ipv4_tcp_syncookies_value: !!str 1
var_nftables_family: !!str inet
var_nftables_table: !!str firewalld
var_selinux_policy_name: !!str targeted
var_selinux_state: !!str enforcing
var_postfix_inet_interfaces: !!str loopback-only
var_multiple_time_servers: !!str 0.rhel.pool.ntp.org,1.rhel.pool.ntp.org,2.rhel.pool.ntp.org,3.rhel.pool.ntp.org
var_sshd_set_keepalive: !!str 1
sshd_idle_timeout_value: !!str 900
var_sshd_set_login_grace_time: !!str 60
sshd_max_auth_tries_value: !!str 4
var_sshd_max_sessions: !!str 10
var_sshd_set_maxstartups: !!str 10:30:60
var_accounts_passwords_pam_faillock_dir: !!str /var/run/faillock
var_auditd_action_mail_acct: !!str root
var_auditd_admin_space_left_action: !!str halt
var_auditd_max_log_file: !!str 6
var_auditd_max_log_file_action: !!str keep_logs
var_auditd_space_left_action: !!str email
